default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  mandrill_api_key: <%= ENV["MANDRILL_API_KEY"] %>
  postmark_api_token: <%= ENV["POSTMARK_API_TOKEN"] %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
